import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { IoMdDownload } from "react-icons/io";
import { BsFillMoonStarsFill } from "react-icons/bs";

import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState, useEffect, useRef } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Typed from "typed.js";
import deved from "../public/venath.jpeg";
import Image from "next/image";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const typedRef = useRef(null);
  

  useEffect(() => {
    // Initialize AOS
    AOS.init({
      duration: 1000, // Duration of animation in milliseconds
      once: true, // Whether animation should only happen once
    });
    

    // Initialize Typed.js
    const options = {
      strings: [
        "Developer",
        "Designer",
        "Content Creator",
        "Athlete",
      ],
      typeSpeed: 100,
      backSpeed: 100,
      loop: true,
    };

    typedRef.current = new Typed(".typed", options);

    return () => {
      // Destroy Typed instance during cleanup to stop animation
      typedRef.current.destroy();
    };
  }, []);

  

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section id ="home" className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Venath</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="venath.pdf"
                  download="venath.pdf"
                >
                  Resume
                </a>
              </li>{" "}
              <IoMdDownload style={{ fontSize: "30px" }} />
            </ul>
          </nav>
          <div className="text-center p-10 py-10" data-aos="fade-in">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Venath Randima
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I'm Venath Randima, currently pursuing my degree in Software
              Engineering at SLIIT. I'm actively seeking collaborations with
              driven individuals who have the ability to adapt to any situation
              and demonstrate a proven potential to foster personal and team
              growth
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="#">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/venath-randima-b3b425281/">
                <AiFillLinkedin />
              </a>
              <a href="https://www.youtube.com/@team_ramp">
                <AiFillYoutube />
              </a>
              <a href="https://github.com/Venath">
                <AiFillGithub />
              </a>
            </div>

            <div className="flex items-center justify-center mt-20">
              <div className="flex items-center justify-center mt-20 relative w-80 h-80 md:w-96 md:h-96 rounded-full overflow-hidden bg-gradient-to-b from-teal-500">
                <Image src={deved} layout="fill" objectFit="cover" />
              </div>
            </div>
            <h1 className="text-3xl md:text-4xl lg:text-5xl ml-8 dark:text-white">
              I'm a{" "}
            </h1>
            <u className="text-4xl dark:text-white">
              <span className="typed text-3xl md:text-4xl lg:text-5xl ml-8 dark:text-white"></span>
            </u>
          </div>
        </section>
        <section>
          {/* <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div> */}

        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since embarking on my undergraduate journey in Software
              Engineering at SLIIT, I've been actively seeking opportunities to
              broaden my horizons. I've engaged in collaborative projects,
              explored various aspects of software development, and honed my
              skills in adapting to different situations. Currently, I'm open to
              collaborations and eager to connect with driven individuals who
              share a passion for growth and innovation
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          {/* <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div> */}
        </section>
        <section>
          <u className="text-4xl py-5 dark:text-white">
          <h3 className="text-4xl py-1 text-center dark:text-white">Academics</h3>
          </u>
          <div className="py-4">
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                First Year First Semester (GPA - 3.07)
              </h4>
              {/*  <ul className="list-disc list-inside text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
       <li>Introduction to Programming (C Language)</li>
        <li>Introduction to Computer Systems</li>
        <li>Communication Skills</li>
        <li>Mathematics for Computing</li> 
      </ul>
    </div>
    <div className="py-5">
      <h4 className="text-2xl py-2 dark:text-white">First Year Second Semester (GPA - 3.4)</h4>
      <ul className="list-disc list-inside text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
     {/*  <li>Object Oriented Concepts (C++ Language)</li>
         <li>Software Process Modeling</li>
        <li>English for Academic Purposes</li>
        <li>Information Systems & Data Modeling</li> 
        <li>Internet & Web Technologies (HTML, PHP, JS)</li>
      </ul>*/}
              {/* <p className="py-2 text-gray-800 dark:text-gray-200">
        Completing a group project on developing a website on "Online Land selling System" using HTML, PHP, CSS, JavaScript.
        Repository: <a href="https://github.com/Venath/LandSale">LandSale</a>
      </p> */}
            </div>
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                First Year Second Semester (GPA - 3.04)
              </h4>
            </div>
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                Second Year First Semester (GPA - 3.06)
              </h4>
            </div>
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                Second Year Second Semester (GPA - 3.39 )
              </h4>
              {/* <p className="py-2 text-gray-800 dark:text-gray-200">
        Completing a group project on developing a web application on "Real Dancing Competition “BornToBattle”" using MERN Technology.
        Repository: <a href="https://github.com/Venath/BornToBattle">BornToBattle</a>
      </p> */}
            </div>
          </div>
        </section>

        <section id="projects" className="min-h-screen">
          <br></br>
          
          <div>
  <u className="text-4xl py-1 dark:text-white">
    
  <div class="container mx-auto p-4">
  <h3 className="text-4xl py-1 text-center dark:text-white">Academic Projects</h3>
</div>

  </u>
  
  {/* <div className="lg:flex gap-10"> */}
  <div class="container mx-auto p-4">



  <div class="bg-gray-100 p-6 rounded-lg shadow-lg">

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-4">

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 class="text-2xl font-bold mb-2">Online Land selling System</h3>
        <p>Completing a group project on developing a website on "Online Land selling System" using HTML, PHP, CSS, JavaScript</p>
        <br/>
        <p className="py-2 text-blue-500 " style={{ display: 'flex', alignItems: 'center' }}>
      <a href="https://github.com/Venath/LandSale">Repository:  LandSale</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
      </div>


      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
    <h3 className="text-2xl font-bold mb-2">Online Medicine and Drug Ordering System</h3>
    <p>Completing a group project on developing a web application on "Online medicine and drug ordering system" using MVC Architecture</p>
    <p className="py-2 text-blue-500 " style={{ display: 'flex', alignItems: 'center' }}>
      <a href="https://github.com/Venath/Med" className="text-blue-500">Repository: Med</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

   <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl my-5">
    <h3 className="text-2xl font-bold mb-2">Real Dancing Competition “BornToBattle”</h3>
    <p>Completing a group project on developing a web application on Real Dancing Competition “BornToBattle” using MERN Technology</p>
    <p className="py-2 text-blue-500 " style={{ display: 'flex', alignItems: 'center' }}>
      <a href="https://github.com/Venath/BornToBattle" className="text-blue-500">Repository: BornToBattle</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl my-5">
    <h3 className="text-2xl font-bold mb-2">Online Art Gallery</h3>
    <p>Creating a mobile app on “Online Art Gallery” using Kotlin</p>
  </div>

  <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl my-5">
    <h3 className="text-2xl font-bold mb-2">Game Of 15</h3>
    <p>Creating a mobile game on “Game Of 15” using Kotlin</p>
    <p className="py-2 text-blue-500 " style={{ display: 'flex', alignItems: 'center' }}>
      <a href="https://github.com/Venath/GameOf15" className="text-blue-500">Repository: GameOf15</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl my-5">
    <h3 className="text-2xl font-bold mb-2">Number Guessing</h3>
    <p>Creating a mobile game on “Number Guessing”</p>
  </div>


    </div>
  </div>

</div>

  {/* <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Completing a group project on developing a website on "Online Land selling System" using HTML, PHP, CSS, JavaScript
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/LandSale">LandSale</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Completing a group project on developing a web application on "Online medicine and drug ordering system" using MVC Architecture
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/Med">Med</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Completing a group project on developing a web application on Real Dancing Competition “BornToBattle” using MERN Technology
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/BornToBattle">BornToBattle</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Creating a mobile app on “Online Art Gallery” using Kotlin
        </h4>
      </li>
    </ul>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Creating a mobile game on “Game Of 15” using Kotlin
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/GameOf15">GameOf15</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Creating a mobile game on “Number Guessing”
        </h4>
      </li>
    </ul>
  </div> */}
</div>

          <div className="py-5">

            <u className="text-4xl py-5 dark:text-white">
            <h3 className="text-4xl py-1 text-center dark:text-white">
                Personal Projects
              </h3>
            </u>

            <div className="container mx-auto p-4">
  <div className="bg-gray-100 p-6 rounded-lg shadow-lg">
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-4">

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating my own portfolio using Next js(2024)</h3>
        <p>Repository: <a href="https://venath.github.io/portfolio/" className="text-blue-500">Portfolio</a></p>
      </div>

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating python program to find gender and birthday using NIC (2019)</h3>
        <p>Repository: <a href="https://github.com/Venath/FindBirthDay" className="text-blue-500">FindBirthDay</a></p>
        <p>Live: <a href="http://venath.pythonanywhere.com/" className="text-blue-500">Online FindDOB</a></p>
      </div>

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating URL Shortener</h3>
        <p>Repository: <a href="https://github.com/Venath/url-shortner" className="text-blue-500">UrlShortener</a></p>
      </div>

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating Facebook clone using react</h3>
        <p>Repository: <a href="https://github.com/Venath/facebook-clone" className="text-blue-500">Facebook Clone</a></p>
      </div>

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-tVenath Randima CVransform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating A Weather App</h3><b>Using JavaScript, Html and CSS</b>
        <p>Repository: <a href="https://github.com/Venath/Weather-app" className="text-blue-500">Weather App</a></p>
        <p>Live: <a href="https://venath.github.io/Weather-App/" className="text-blue-500">Weather App</a></p>
      </div>

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating A Tic Tac Toe Game </h3><b>Using Java</b>
        <p style={{ display: 'flex', alignItems: 'center' }}>Repository: <a href="https://github.com/Venath/TicTacToe" className="text-blue-500">TicTacToe</a>  <AiFillGithub style={{ marginLeft: '0.5rem' }} /></p>
      </div>

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating A Memory Game </h3><b>Using Javascript</b>
        <p style={{ display: 'flex', alignItems: 'center' }}>Repository: <a href="https://github.com/Venath/TicTacToe" className="text-blue-500">Memory Game</a>  <AiFillGithub style={{ marginLeft: '0.5rem' }} /></p>
        <p>Live: <a href="https://venath.github.io/Memory_Game/" className="text-blue-500">Memory Game</a></p>

      </div>

      <div className="flex flex-col bg-white p-4 shadow-lg transform transition-transform hover:scale-105 hover:shadow-xl">
        <h3 className="text-2xl font-bold mb-2">Creating a Currency Converter</h3><b>Using Javascript</b>
        <p style={{ display: 'flex', alignItems: 'center' }}>Repository: <a href="https://github.com/Venath/currency_converter" className="text-blue-500">Currency Converter</a>  <AiFillGithub style={{ marginLeft: '0.5rem' }} /></p>
       

      </div>

    </div>
  </div>
</div>



          </div>
        </section>

      </main>
    </div>
  );
}
