import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { IoMdDownload } from "react-icons/io";
import { BsFillMoonStarsFill } from "react-icons/bs";

import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState, useEffect, useRef } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Typed from "typed.js";
import deved from "../public/venath.jpeg";
import Image from "next/image";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const typedRef = useRef(null);
  

  useEffect(() => {
    // Initialize AOS
    AOS.init({
      duration: 1000, // Duration of animation in milliseconds
      once: true, // Whether animation should only happen once
    });
    

    // Initialize Typed.js
    const options = {
      strings: [
        "Developer",
        "Designer",
        "Content Creator",
        "Athlete",
      ],
      typeSpeed: 100,
      backSpeed: 100,
      loop: true,
    };

    typedRef.current = new Typed(".typed", options);

    return () => {
      // Destroy Typed instance during cleanup to stop animation
      typedRef.current.destroy();
    };
  }, []);

  

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section id ="home" className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Venath</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="venath.pdf"
                  download="venath.pdf"
                >
                  Resume
                </a>
              </li>{" "}
              <IoMdDownload style={{ fontSize: "30px" }} />
            </ul>
          </nav>
          <div className="text-center p-10 py-10" data-aos="fade-in">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Venath Randima
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I'm Venath Randima, currently pursuing my degree in Software
              Engineering at SLIIT. I'm actively seeking collaborations with
              driven individuals who have the ability to adapt to any situation
              and demonstrate a proven potential to foster personal and team
              growth
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="#">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/venath-randima-b3b425281/">
                <AiFillLinkedin />
              </a>
              <a href="https://www.youtube.com/@team_ramp">
                <AiFillYoutube />
              </a>
              <a href="https://github.com/Venath">
                <AiFillGithub />
              </a>
            </div>

            <div className="flex items-center justify-center mt-20">
              <div className="flex items-center justify-center mt-20 relative w-80 h-80 md:w-96 md:h-96 rounded-full overflow-hidden bg-gradient-to-b from-teal-500">
                <Image src={deved} layout="fill" objectFit="cover" />
              </div>
            </div>
            <h1 className="text-3xl md:text-4xl lg:text-5xl ml-8 dark:text-white">
              I'm a{" "}
            </h1>
            <u className="text-4xl dark:text-white">
              <span className="typed text-3xl md:text-4xl lg:text-5xl ml-8 dark:text-white"></span>
            </u>
          </div>
        </section>
        <section>
          {/* <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div> */}
          <div className="lg:flex gap-10">
            {/* <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div> */}
            {/* <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              
              <h3 className="text-lg font-medium pt-8 pb-2">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Development Tools I Use</h4>
              <p className="text-gray-800 py-1">Visual Studio Code</p>
              <p className="text-gray-800 py-1">Git</p>
              <p className="text-gray-800 py-1">Next.js</p>
              <p className="text-gray-800 py-1">Node.js</p>
            </div> */}
            {/* <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Consulting Tools I Use</h4>
              <p className="text-gray-800 py-1">Zoom</p>
              <p className="text-gray-800 py-1">Skype</p>
              <p className="text-gray-800 py-1">Google Meet</p>
            </div> */}
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since embarking on my undergraduate journey in Software
              Engineering at SLIIT, I've been actively seeking opportunities to
              broaden my horizons. I've engaged in collaborative projects,
              explored various aspects of software development, and honed my
              skills in adapting to different situations. Currently, I'm open to
              collaborations and eager to connect with driven individuals who
              share a passion for growth and innovation
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          {/* <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div> */}
        </section>
        <section>
          <u className="text-4xl py-5 dark:text-white">
            <h3 className="text-4xl py-1 dark:text-white">Academics</h3>
          </u>
          <div className="py-4">
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                First Year First Semester (GPA - 3.07)
              </h4>
              {/*  <ul className="list-disc list-inside text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
       <li>Introduction to Programming (C Language)</li>
        <li>Introduction to Computer Systems</li>
        <li>Communication Skills</li>
        <li>Mathematics for Computing</li> 
      </ul>
    </div>
    <div className="py-5">
      <h4 className="text-2xl py-2 dark:text-white">First Year Second Semester (GPA - 3.4)</h4>
      <ul className="list-disc list-inside text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
     {/*  <li>Object Oriented Concepts (C++ Language)</li>
         <li>Software Process Modeling</li>
        <li>English for Academic Purposes</li>
        <li>Information Systems & Data Modeling</li> 
        <li>Internet & Web Technologies (HTML, PHP, JS)</li>
      </ul>*/}
              {/* <p className="py-2 text-gray-800 dark:text-gray-200">
        Completing a group project on developing a website on "Online Land selling System" using HTML, PHP, CSS, JavaScript.
        Repository: <a href="https://github.com/Venath/LandSale">LandSale</a>
      </p> */}
            </div>
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                First Year Second Semester (GPA - 3.04)
              </h4>
            </div>
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                Second Year First Semester (GPA - 3.06)
              </h4>
            </div>
            <div className="py">
              <h4 className="text-2xl py dark:text-white">
                Second Year Second Semester (GPA )
              </h4>
              {/* <p className="py-2 text-gray-800 dark:text-gray-200">
        Completing a group project on developing a web application on "Real Dancing Competition “BornToBattle”" using MERN Technology.
        Repository: <a href="https://github.com/Venath/BornToBattle">BornToBattle</a>
      </p> */}
            </div>
          </div>
        </section>

        <section id="projects" className="min-h-screen">
          <br></br>
          <div>
  <u className="text-4xl py-1 dark:text-white">
    <h3 className="text-4xl py-1 dark:text-white">Academic Projects</h3>
  </u>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Completing a group project on developing a website on "Online Land selling System" using HTML, PHP, CSS, JavaScript
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/LandSale">LandSale</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Completing a group project on developing a web application on "Online medicine and drug ordering system" using MVC Architecture
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/Med">Med</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Completing a group project on developing a web application on Real Dancing Competition “BornToBattle” using MERN Technology
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/BornToBattle">BornToBattle</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Creating a mobile app on “Online Art Gallery” using Kotlin
        </h4>
      </li>
    </ul>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Creating a mobile game on “Game Of 15” using Kotlin
        </h4>
      </li>
    </ul>
    <p className="py-2 text-gray-800 dark:text-gray-200" style={{ display: 'flex', alignItems: 'center' }}>
      Repository: <a href="https://github.com/Venath/GameOf15">GameOf15</a>
      <AiFillGithub style={{ marginLeft: '0.5rem' }} />
    </p>
  </div>

  <div className="py-5">
    <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
        <h4 className="text-2xl py-2 dark:text-white">
          Creating a mobile game on “Number Guessing”
        </h4>
      </li>
    </ul>
  </div>
</div>

          <div className="py-5">
            <u className="text-4xl py-5 dark:text-white">
              <h3 className="text-3xl py-1 dark:text-white">
                Personal Projects
              </h3>
            </u>
            <div className="py-5">
            <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
              <h4 className="text-2xl py-2 dark:text-white">
                Creating my own portfolio (2024)
              </h4>
              </li>
    </ul>
              <p className="py-2 text-gray-800 dark:text-gray-200">
                Repository:{" "}
                <a href="https://venath.github.io/portfolio/">Portfolio</a>
              </p>
            </div>
            <div className="py-5">
            <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
              <h4 className="text-2xl py-2 dark:text-white">
                Creating python program to find gender and birthday using NIC
                (2019)
              </h4>
              </li>
    </ul>
              <p className="py-2 text-gray-800 dark:text-gray-200">
                Repository:{" "}
                <a href="https://github.com/Venath/FindBirthDay">
                  FindBirthDay
                </a>
                <br></br>
                <a href="http://venath.pythonanywhere.com/">
                 Online FindDOB
                </a>
              </p>
            </div>

            <div className="py-5">
            <ul className="list-disc text-md py-2 leading-8 text-gray-800 text-[30px] dark:text-gray-200">
      <li>
              <h4 className="text-2xl py-2 dark:text-white">
                Creating URL Shortener
              </h4>
              </li>
    </ul>
              <p className="py-2 text-gray-800 dark:text-gray-200">
                Repository:{" "}
                <a href="https://github.com/Venath/url-shortner">
                  UrlShortener
                </a>
            
              </p>
            </div>


          </div>
        </section>
        <section id="contact" className="min-h-screen">
         <h1>Helloooooo</h1>
        </section>
      </main>
    </div>
  );
}
